#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
NAME="/notes.txt"
FPATH="$DIR$NAME"

while getopts ":hcr:t:s:" opt; do
	case ${opt} in
		h )
			printf "%s\n" "Usage: notes [-hc] [-t] [-r] [-s] text"
			printf "%s\n" "h: Help"
			printf "%s\n" "c: Clear notes"
			printf "%s\n" "t: Timer [min]"
			printf "%s\n" "r: Retrieve [number]"
			printf "%s\n" "s: Timer [sec]"
			exit 1
			;;
		t )
			target=$OPTARG
			dat="\n`date`: "
			nl="\n"
			not="$3"
			sleep $(($OPTARG*60)) && echo -ne "\007$dat${not:0:$((${#not}+1))}$nl" &
			;;
		s )
			target=$OPTARG
			dat="\n`date`: "
			nl="\n"
			not="$3"
			sleep $OPTARG && echo -ne "\007$dat${not:0:$((${#not}+1))}$nl" &
			;;
		r )
			target=$OPTARG
			tail -n $OPTARG $FPATH
			exit 1
			;;
		c )
			echo "" > $FPATH
			printf "%s\n" "Notes cleared!"
			exit 1
			;;
		\? )
			echo "Invalid option: $OPTARG" 1>&2
			exit 1
			;;
		: )
      			echo "Invalid option: $OPTARG requires an argument" 1>&2
      			exit 1
			;;
	esac
done
if [ "$#" -le 0 ]; then
	printf "%s\n" 'Usage: notes [-hc] [-t] [-r] [-s] "text"'
	exit 1
fi
shift $((OPTIND -1))
dat="`date`: "
nl="\n"
not="$1$nl"
printf "$dat${not:0:$((${#not}))}" >> $FPATH
printf "%s\n" "Recorded!"
